### ISSUE TITLE
Is it possible to run chain_demo.py like PIPs?

### ISSUE THREAD

**Issue by riponazad** [wkbian/Context-PIPs#1]
I have tried to run it and encountered some errors. Since you haven't provided any instruction, I was thinking of making sure first before spending time.
TIA

This is the first error while running chain_demo.py

In "pips.py", line 546, in forward
    ffeats_x9 = ffeat_x9.unsqueeze(1).repeat(1, S, 1, 1, 1) # B, S, N, T, C
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

**Comment by wkbian** [comment]
Yes. The `chain_demo.py` script would call PIPs by default. You can modify [Line 54](https://github.com/wkbian/Context-PIPs/blob/d8bc4fe7799b046d90cf5bb47331aac28cad8922/chain_demo.py#L54) and add necessary variables `feat_x9_init` and `query_init`  to run our Context-PIPs.

Here is a sample code snippet.
```
        feat_init = None
        feat_x9_init = None
        query_init = None
        while not done:
            end_frame = cur_frame + 8

            rgb_seq = rgbs[:,cur_frame:end_frame]
            S_local = rgb_seq.shape[1]
            rgb_seq = torch.cat([rgb_seq, rgb_seq[:,-1].unsqueeze(1).repeat(1,8-S_local,1,1,1)], dim=1)

            # outs = model(traj_e[:,cur_frame].reshape(1, -1, 2), rgb_seq, iters=6, feat_init=feat_init, return_feat=True)
            outs = model(traj_e[:,cur_frame].reshape(1, -1, 2), rgb_seq, iters=6, feat_init=feat_init, return_feat=True, feat_x9_init=feat_x9_init, query_init=query_init)
            preds = outs[0]
            vis = outs[2] # B, S, 1
            feat_init = outs[3]
            feat_x9_init = outs[5]
            query_init = outs[6]
```

**Comment by riponazad** [comment]
Thanks for your response. I will try it later.
